version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pccontroller"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6wlstkxlu1xs"
s3_prefix = "pccontroller"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
